#! /usr/bin/env sh

CLD_DST=$CLD_MOUNT$CLD_SUBPATH

. cldsync-trap

echo "inotify $CLD_SRC onto $CLD_DST"
mkdir -p "$CLD_SRC"
mkdir -p "$CLD_DST"
rsync -auv -T /tmp --size-only --chmod=755 $CLD_SRC $CLD_DST
while true; do
  if [ -z "$CLD_INOTIFY_EXCLUDE" ]; then 
    inotifywait -r -t $CLD_TIMESYNC -e close_write,move,delete $CLD_SRC
  else
    inotifywait -r -t $CLD_TIMESYNC -e close_write,move,delete --exclude $CLD_INOTIFY_EXCLUDE $CLD_SRC
  fi
  if [ ! -n "$(ls -1A $CLD_MOUNT)" ]; then
    echo "Nothing found in $CLD_MOUNT, giving up!"
    exit 2
  fi
  rsync -auv -T /tmp --size-only --chmod=$CLD_FILEMODE $CLD_SRC $CLD_DST
done
