#! /usr/bin/env sh

. cldsync-trap

while true; do
    if [ -z "$(ps aux | grep "[m]ount.davfs")" ] || [ -z "$(ls -1A "$CLD_MOUNT")" ]; then
        exit 
    fi
    ls "$CLD_MOUNT"
    sleep $CLD_LOOP_PERIOD
done
