#! /usr/bin/env sh

#echo $CLD_URL
#echo $CLD_USERNAME
#echo $CLD_PASSWORD

#echo $CLD_MOUNT
#echo $CLD_UID
#echo $CLD_GID
#echo $CLD_DIRMODE
#echo $CLD_FILEMODE
MOUNTPIDF=/var/run/mount.davfs/mnt-webdrive.pid

if [ -z "$CLD_URL" ]; then
    echo "Nothing found in CLD_URL to mount, giving up!" 
    exit 1
fi

if [ ! -d $CLD_MOUNT ]; then
    mkdir -p $CLD_MOUNT
fi

if [ ! -z "$CLD_USERNAME" ]; then
    echo "$CLD_MOUNT $CLD_USERNAME $CLD_PASSWORD" > /etc/davfs2/secrets
fi
unset CLD_PASSWORD                                              

if [ -n "$(env | grep "DAVFS2_")" ]; then
    echo "[$CLD_MOUNT]" > /etc/davfs2/davfs2.conf
    for VAR in $(env); do
        if [ -n "$(echo "$VAR" | grep -E '^DAVFS2_')" ]; then
            OPT_NAME=$(echo "$VAR" | sed -r "s/DAVFS2_([^=]*)=.*/\1/g" | tr '[:upper:]' '[:lower:]')
            VAR_FULL_NAME=$(echo "$VAR" | sed -r "s/([^=]*)=.*/\1/g")
            VAL=$(eval echo \$$VAR_FULL_NAME)
            echo "$OPT_NAME $VAL" >> /etc/davfs2/davfs2.conf
        fi
    done
fi

if [ -f $MOUNTPIDF ]; then
    echo "Clear before pid file $MOUNTPIDF"
    rm -f $MOUNTPIDF
fi

mount -t davfs $CLD_URL $CLD_MOUNT \
    -o uid=$CLD_UID,gid=$CLD_GID,dir_mode=$CLD_DIRMODE,file_mode=$CLD_FILEMODE

if [ $? -eq 0 ] && [ -n "$(ls -1A $CLD_MOUNT)" ]; then
    echo "Mounted $CLD_URL onto $CLD_MOUNT"
    exec "$@"
else
    echo "Nothing found in $CLD_MOUNT, giving up!"
    exit 2
fi
